do_test:
	sh ./integration_testing.sh &
	sh ./unit_testing.sh &

do_integration_test:
	sh ./integration_testing.sh &

do_unit_test:
	sh ./unit_testing.sh &

stop_test:
	sh ./stop_unit_testing.sh &
	sh ./stop_integration_testing.sh &
stop_integration_test:
	sh ./stop_integration_testing.sh &

stop_unit_test:
	sh ./stop_unit_testing.sh &